Flask_blog/flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

Flask_blog/flask_blog/main/routes.py
from flask import render_template, request, Blueprint
from flask_blog.models import Post


main = Blueprint('main', __name__)

# This forward slash(/) is the root page or the home page of this webapp
@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    # The order_by(Post.date_posted.desc()) is added to make sure that the latest post is found at the top of the blog. The pageinate is to limit the number of posts loaded per page, therefore numbers of how many post should be available per page is inserted into it, and the reset of the unloaded page will be in the next on at the footer of the blog
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

Flask_blog/flask_blog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flask_blog import db
from flask_blog.models import Post
from flask_blog.posts.forms import PostForm
posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required  # Login is rrequired for this page to be accessable
def new_post():
    form = PostForm()
    if form.validate_on_submit():  # After clicking on the submit button and nothing goes wrong, then update Post to the database
        post = Post(title=form.title.data, content=form.content.data, author=current_user)  # Creating Post Table in the database
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


# Here, it create a rouute based on the unique id each post has
@posts.route("/post/<int:post_id>")
def post(post_id):# It takes post_id as an input
    # This gets the content that exist at the id.....if nothing exist there, it return 404 (Page not found)
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    # If post_id isnt found, it returns 404 error
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:  # This is to ensure that only the author can edit their post
        abort(403)  # This is the http response for a forbidden route
    form = PostForm()
    if form.validate_on_submit():  # When User clicks on the submit button, It update the post content to the new content user inputed
        post.title = form.title.data
        post.content = form.content.data
        # Here no need to add before commiting, because its already in the database, we are just updating it
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET': # If its a get request, it populate the title and content with the current post
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:  # This is to ensure that only the author can edit their post
        abort(403)  # This is the http response for a forbidden route
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

Flask_blog/flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flask_blog.users.utils import save_picture, send_reset_email


user = Blueprint('users', __name__)

@user.route("/register", methods=['GET', 'POST']) # For get and post request
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit(): # When you click on submit button in registeration
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data,
                     password=hashed_password) # Storing user info into user class
        db.session.add(user) # About to add user to the database
        db.session.commit() # Push user to database
        # sends a message to affirm that user account have been created
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login')) # Takes user to login page
    return render_template('register.html', title='Register', form=form)


@user.route("/login", methods=['GET', 'POST']) # For get and post request
def login():
    if current_user.is_authenticated: # This is to check if user is logged in. if true, then when user clicks on register, it redirects to home
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit(): # After clicking on the submit button, check if the email, and password is equal to the admin, else you cannot login for now
        user = User.query.filter_by(email=form.email.data).first()
        # Checks if email doesnt exist before, and if password is correct
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            # After logging in, it returns back to the present page before logging in
            next_page = request.args.get('next')
            # sends a message to affirm that user account have been created
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@user.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@user.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():  # After clicking on the submit button and nothing goes wrong, then update username and email to the newly inputed data
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit() # Update user info in the database
        flash('Your account has been updated!', 'success')
        # including this is to avoid resubmition when page is reloaded
        return redirect(url_for('users.account'))
    elif request.method == 'GET':  # This will populate the username and email field when the 'account' page is loaded
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)

@user.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    # this is to get all the posts that the username clicked has uploaded on the webpage
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)  # The order_by(Post.date_posted.desc()) is added to make sure that the latest post is found at the top of the blog. back slash is for breaking the line to write in the next line
    return render_template('user_posts.html', posts=posts, user=user)

@user.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated: # This is to check if user is logged in. if true, then when user clicks on register, it redirects to home
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit(): # After submitting the reset request, send an email message to the users email on how to reset there password
        user = User.query.filter_by(email=form.email.data).first()  # Fetch user email
        send_reset_email(user)  # Send mail to user email
        # Show user confirmation that the message has been sent to their mail
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login')) # Redirects user to the login page
    return render_template('reset_request.html', title='Reset Password', form=form)


@user.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:  # This is to check if user is logged in. if true, then when user clicks on register, it redirects to home
        return redirect(url_for('main.home'))
    # This gets the user's id from 'models.py'
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('user.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():  # When you click on submit button in registration
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()# Push user to database
        # sends a message to affirm that user account have been created
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login')) # Takes user to login page
    return render_template('reset_token.html', title='Reset Password', form=form)

Flask_blog/flask_blog/templates/about.html
{% extends "layout.html" %} {% block content %}

<h2>About Me</h2>
<p>
  Welcome to my blog! I'm [Your Name], and I'm excited to share my thoughts,
  experiences, and insights with you through this platform. Whether you stumbled
  upon my blog by chance or you're a regular reader, I'm glad you're here.
</p>
<h2>Who Am I?</h2>
<p>
  I'm a [your profession/interests] enthusiast with a passion for [mention a few
  things you're passionate about]. I believe in the power of [something you
  strongly believe in, like continuous learning, creativity, etc.]. Through this
  blog, I aim to [state your blogging goals, like sharing knowledge, inspiring
  others, or fostering discussions].
</p>
<h3>What You'll Find Here</h3>
<p>
  This blog is a space where I'll be discussing [mention the main topics you'll
  cover, such as technology, travel, lifestyle, etc.]. Expect to find [briefly
  describe the type of content you'll share, such as informative articles,
  personal stories, tips and tricks, etc.].
</p>
<h3>Why I Started This Blog</h3>
<p>
  The idea behind starting this blog stemmed from my desire to [explain your
  motivation, whether it's sharing your expertise, connecting with like-minded
  individuals, or documenting your journey]. I believe that [mention what you
  hope your readers will gain from your blog, such as insights, inspiration, or
  practical advice].
</p>
<h3>Join the Conversation</h3>
<p>
  I encourage you to join the conversation by leaving comments on my posts. Your
  thoughts, feedback, and questions are always welcome. Let's create a vibrant
  community where we can learn from each other and engage in meaningful
  discussions.
</p>
<h3>Get in Touch</h3>
<p>
  Feel free to [mention how readers can get in touch with you, such as through
  social media links or a contact form]. I'm excited to connect with you and
  hear your thoughts.
</p>
<p></p>

<p>
  Thank you for being a part of this journey with me. I look forward to sharing
  valuable content and building a community of readers who are as passionate
  about [your main topics] as I am. Happy reading! Warm regards, [Your Name]
  Remember to personalize the content, fill in the details relevant to you, and
  tailor the tone to match your style and audience. An "About" page is a great
  opportunity to introduce yourself to your readers, so make it genuine and
  inviting!
</p>

{% endblock content %}

Flask_blog/flask_blog/templates/account.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{image_file}}">
        <div class="media-body">
            <h2 class="account-heading">{{current_user.username}}</h2>
            <p class="text-secondary">{{current_user.email}}</p>
        </div>
    </div>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <!-- ----------- Username ------------- -->
            <div class="form-group">
                {{ form.username.label(class="form-control-label")}} {% if form.username.errors %} {{ form.username(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.username(class="form-control form-control-lg")}} {% endif %}
            </div>
            <!-- ----------- Email ---------- -->
            <div class="form-group">
                {{ form.email.label(class="form-control-label")}} {% if form.email.errors %} {{ form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.email(class="form-control form-control-lg")}} {% endif %}
            </div>
            <!-- ----------- Picture ------------- -->
            <div class="form-group">
                {{ form.picture.label()}} {{ form.picture(class='form-control-file') }} {% if form.picture.errors %} {% for error in form.picture.errors%}
                <span class="text-danger"> {{ error }} </span><br> {% endfor %} {% endif %}
            </div>
        </fieldset>
        <!-- --------- Submit ---------- -->
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>
{% endblock content %}

Flask_blog/flask_blog/templates/create_post.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{legend}}</legend>
            <!-- --------- Title --------- -->
            <div class="form-group">
                {{ form.title.label(class="form-control-label")}} {% if form.title.errors %} {{ form.title(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.title(class="form-control form-control-lg")}} {% endif %}
            </div>
            <!-- --------- Content --------- -->
            <div class="form-group">
                {{ form.content.label(class="form-control-label")}} {% if form.content.errors %} {{ form.content(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.content(class="form-control form-control-lg")}} {% endif %}
            </div>
        </fieldset>
        <!-- ---------- Submit-btn ----------- -->
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>
{% endblock content %}

Flask_blog/flask_blog/templates/home.html
{% extends "layout.html" %} {% block content %} {% for post in posts.items %}
<article class="media content-section">
  <img
    class="rounded-circle article-img"
    src="{{url_for('static', filename='profile_pics/' + post.author.image_file)}}"
    alt=""
  />
  <div class="media-body">
    <div class="article-metadata">
      <a
        class="mr-2"
        href="{{url_for('users.user_posts', username=post.author.username)}}"
        >{{ post.author.username }}</a
      >
      <small class="text-muted"
        >{{ post.date_posted.strftime('%Y-%m-%d') }}</small
      >
    </div>
    <h2>
      <a
        class="article-title"
        href="{{ url_for('posts.post', post_id=post.id) }}"
        >{{ post.title }}</a
      >
    </h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %} {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
left_current=1, right_current=2) %} {%if page_num%} {%if posts.page ==
page_num%}
<a href="{{url_for('main.home', page=page_num)}}" class="btn-info btn mb-4"
  >{{page_num}}</a
>
{%else%}
<a
  href="{{url_for('main.home', page=page_num)}}"
  class="btn-outline-info btn mb-4"
  >{{page_num}}</a
>
{%endif%} {%else%} ... {%endif%} {%endfor%} {% endblock content %}

Flask_blog/flask_blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}"> {%if title %}
    <title>Flask Blog - {{title}}</title>
    {%else%}
    <title>Flask Blog</title>
    {%endif%}



</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container fle justify-content-between">
                <a class="navbar-brand mr-4" href="/">Flask Blog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse flex-row justify-content-between" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
                        <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{url_for('posts.new_post')}}">New Post</a>
                        <a class="nav-item nav-link" href="{{url_for('users.account')}}">Account</a>
                        <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Logout</a> {% else %}
                        <a class="nav-item nav-link" href="{{url_for('users.login')}}">Login</a>
                        <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register</a> {%endif%}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                <!-- get_flashed_messages will get the flashed message sent to the template -->
                {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
                <div class="alert alert-{{category}}">
                    {{message}}
                </div>
                {% endfor %} {% endif %}{% endwith %} {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">Latest Posts</li>
                            <li class="list-group-item list-group-item-light">Announcements</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
</body>

</html>

Flask_blog/flask_blog/templates/login.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
  <form action="" method="post">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Log in</legend>
      <!-- --------- Email --------- -->
      <div class="form-group mb-2">
        {{ form.email.label(class="form-control-label")}} {% if
        form.email.errors %} {{ form.email(class="form-control form-control-lg
        is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span> {% endfor %}
        </div>
        {% else %} {{ form.email(class="form-control form-control-lg")}} {%
        endif %}
      </div>
      <!-- --------- Password --------- -->
      <div class="form-group mb-2">
        {{ form.password.label(class="form-control-label")}} {% if
        form.password.errors %} {{ form.password(class="form-control
        form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span> {% endfor %}
        </div>
        {% else %} {{ form.password(class="form-control form-control-lg")}} {%
        endif %}
      </div>
      <!-- ---------- Remember ---------- -->
      <div class="form-check">
        {{ form.remember(class="form-check-input")}} {{
        form.remember.label(class="form-check-label")}}
      </div>
    </fieldset>
    <!-- ---------- Submit-btn ----------- -->
    <div class="form-group p-2">
      {{ form.submit(class="btn btn-outline-info")}}
      <small class="text-muted p-2">
        <a href="{{url_for('users.reset_request')}}">Forgot Password?</a>
      </small>
    </div>
  </form>
</div>
<div class="border-top pt-3 mb-2">
  <small class="text-muted">
    Need an account?
    <a href="{{url_for('users.register')}}" class="ml-2">Sign Up Now</a>
  </small>
</div>
{% endblock content %}

Flask_blog/flask_blog/templates/post.html
{% extends "layout.html" %} {% block content %}
<article class="media content-section">
  <img
    class="rounded-circle article-img"
    src="{{url_for('static', filename='profile_pics/' + post.author.image_file)}}"
    alt=""
  />
  <div class="media-body">
    <div class="article-metadata">
      <a
        class="mr-2"
        href="{{url_for('users.user_posts', username=post.author.username)}}"
        >{{ post.author.username }}</a
      >
      <small class="text-muted"
        >{{ post.date_posted.strftime('%Y-%m-%d') }}</small
      >
      {% if post.author == current_user%}
      <div class="">
        <a
          href="{{url_for('posts.update_post', post_id=post.id)}}"
          class="btn btn-secondary btn-sm m-1"
          >Update</a
        >
        <button
          type="button"
          class="btn btn-danger btn-sm m-1"
          data-bs-toggle="modal"
          data-bs-target="#deleteModal"
        >
          Delete
        </button>
      </div>
      {%endif%}
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>

<!-- Modal -->
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  aria-labelledby="deleteModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
          Close
        </button>
        <form
          action="{{ url_for('posts.delete_post', post_id=post.id)}}"
          method="POST"
        >
          <input type="submit" class="btn btn-danger" value="Delete" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

Flask_blog/flask_blog/templates/register.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
  <form action="" method="post">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Join Us Today</legend>
      <!-- ----------- Username ------------- -->
      <div class="form-group">
        {{ form.username.label(class="form-control-label")}} {% if
        form.username.errors %} {{ form.username(class="form-control
        form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
          <span>{{ error }}</span> {% endfor %}
        </div>
        {% else %} {{ form.username(class="form-control form-control-lg")}} {%
        endif %}
      </div>
      <!-- ----------- Email ---------- -->
      <div class="form-group">
        {{ form.email.label(class="form-control-label")}} {% if
        form.email.errors %} {{ form.email(class="form-control form-control-lg
        is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span> {% endfor %}
        </div>
        {% else %} {{ form.email(class="form-control form-control-lg")}} {%
        endif %}
      </div>
      <!-- ------------ Password ------------ -->
      <div class="form-group">
        {{ form.password.label(class="form-control-label")}} {% if
        form.password.errors %} {{ form.password(class="form-control
        form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span> {% endfor %}
        </div>
        {% else %} {{ form.password(class="form-control form-control-lg")}} {%
        endif %}
      </div>
      <!-- ---------- Confirm Passwprd --------- -->
      <div class="form-group">
        {{ form.confirm_password.label(class="form-control-label")}} {% if
        form.confirm_password.errors %} {{
        form.confirm_password(class="form-control form-control-lg is-invalid")}}
        <div class="invalid-feedback">
          {% for error in form.confirm_password.errors %}
          <span>{{ error }}</span> {% endfor %}
        </div>
        {% else %} {{ form.confirm_password(class="form-control
        form-control-lg")}} {% endif %}
      </div>
    </fieldset>
    <!-- --------- Submit ---------- -->
    <div class="form-group">{{ form.submit(class="btn btn-outline-info")}}</div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted">
    Already have an account?
    <a href="{{url_for('users.login')}}" class="ml-2">Sign In</a>
  </small>
</div>
{% endblock content %}

Flask_blog/flask_blog/templates/reset_request.html
{% extends "layout.html" %} {% block content %}
<div class="content-section">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <!-- --------- Email --------- -->
            <div class="form-group mb-3">
                {{ form.email.label(class="form-control-label")}} {% if form.email.errors %} {{ form.email(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %} {{ form.email(class="form-control form-control-lg")}} {% endif %}
            </div>
        </fieldset>
        <!-- ---------- Submit-btn ----------- -->
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info")}}
        </div>
    </form>
</div>
{% endblock content %}

Flask_blog/flask_blog/templates/user_posts.html
{% extends "layout.html" %} {% block content %}
<h1 class="mb-3">Posts by {{user.username}} {{posts.total}}</h1>
{% for post in posts.items %}
<article class="media content-section">
  <img
    class="rounded-circle article-img"
    src="{{url_for('static', filename='profile_pics/' + post.author.image_file)}}"
    alt=""
  />
  <div class="media-body">
    <div class="article-metadata">
      <a
        class="mr-2"
        href="{{url_for('users.user_posts', username=post.author.username)}}"
        >{{ post.author.username }}</a
      >
      <small class="text-muted"
        >{{ post.date_posted.strftime('%Y-%m-%d') }}</small
      >
    </div>
    <h2>
      <a
        class="article-title"
        href="{{ url_for('posts.post', post_id=post.id) }}"
        >{{ post.title }}</a
      >
    </h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %} {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
left_current=1, right_current=2) %} {%if page_num%} {%if posts.page ==
page_num%}
<a
  href="{{url_for('users.user_posts', username=user.username, page=page_num)}}"
  class="btn-info btn mb-4"
  >{{page_num}}</a
>
{%else%}
<a
  href="{{url_for('user.user_posts', username=user.username, page=page_num)}}"
  class="btn-outline-info btn mb-4"
  >{{page_num}}</a
>
{%endif%} {%else%} ... {%endif%} {%endfor%} {% endblock content %}